version: '3'

volumes:
  node_modules:

services:
  app:
    container_name: app
    build: .
    volumes:
      - ../:/app
      - ../node_modules:/app/node_modules
    ports:
      - '3000:3000'
    command: /bin/sh -c "while sleep 1000; do :; done"
